import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/ui/tubelight-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar
          items={[
            { name: "Home", url: "/#home", iconKey: "home" },
            { name: "Projects", url: "/#projects", iconKey: "briefcase" },
            { name: "About", url: "/#about", iconKey: "user" },
            { name: "Resume", url: "/resume", iconKey: "fileText" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
